spring.application.name=SpringDataRestApplication

# MariaDB Configuration
spring.datasource.url=jdbc:mariadb://mariadb:3306/compagnie
spring.datasource.username=root
spring.datasource.password=2003
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.data.rest.base-path=/api

# Actuator Configuration for Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true